packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  better-sqlite3: true
  esbuild: true
overrides:
  drizzle-orm: '0.38.4'
  better-sqlite3: '11.9.1'
peerDependencyRules:
  ignoreMissing:
    - '@libsql/client'
