/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout.index'
import { Route as AdminLayoutThemesIndexRouteImport } from './routes/admin/_layout.themes.index'
import { Route as AdminLayoutTagsIndexRouteImport } from './routes/admin/_layout.tags.index'
import { Route as AdminLayoutSettingsIndexRouteImport } from './routes/admin/_layout.settings.index'
import { Route as AdminLayoutPostsIndexRouteImport } from './routes/admin/_layout.posts.index'
import { Route as AdminLayoutPluginsIndexRouteImport } from './routes/admin/_layout.plugins.index'
import { Route as AdminLayoutMediaIndexRouteImport } from './routes/admin/_layout.media.index'
import { Route as AdminLayoutCommentsIndexRouteImport } from './routes/admin/_layout.comments.index'
import { Route as AdminLayoutCategoriesIndexRouteImport } from './routes/admin/_layout.categories.index'
import { Route as AdminLayoutPostsNewRouteImport } from './routes/admin/_layout.posts.new'
import { Route as AdminLayoutPostsIdRouteImport } from './routes/admin/_layout.posts.$id'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutThemesIndexRoute = AdminLayoutThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutTagsIndexRoute = AdminLayoutTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsIndexRoute =
  AdminLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPostsIndexRoute = AdminLayoutPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutPluginsIndexRoute = AdminLayoutPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMediaIndexRoute = AdminLayoutMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCommentsIndexRoute =
  AdminLayoutCommentsIndexRouteImport.update({
    id: '/comments/',
    path: '/comments/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCategoriesIndexRoute =
  AdminLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPostsNewRoute = AdminLayoutPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutPostsIdRoute = AdminLayoutPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/posts/$id': typeof AdminLayoutPostsIdRoute
  '/admin/posts/new': typeof AdminLayoutPostsNewRoute
  '/admin/categories/': typeof AdminLayoutCategoriesIndexRoute
  '/admin/comments/': typeof AdminLayoutCommentsIndexRoute
  '/admin/media/': typeof AdminLayoutMediaIndexRoute
  '/admin/plugins/': typeof AdminLayoutPluginsIndexRoute
  '/admin/posts/': typeof AdminLayoutPostsIndexRoute
  '/admin/settings/': typeof AdminLayoutSettingsIndexRoute
  '/admin/tags/': typeof AdminLayoutTagsIndexRoute
  '/admin/themes/': typeof AdminLayoutThemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/posts/$id': typeof AdminLayoutPostsIdRoute
  '/admin/posts/new': typeof AdminLayoutPostsNewRoute
  '/admin/categories': typeof AdminLayoutCategoriesIndexRoute
  '/admin/comments': typeof AdminLayoutCommentsIndexRoute
  '/admin/media': typeof AdminLayoutMediaIndexRoute
  '/admin/plugins': typeof AdminLayoutPluginsIndexRoute
  '/admin/posts': typeof AdminLayoutPostsIndexRoute
  '/admin/settings': typeof AdminLayoutSettingsIndexRoute
  '/admin/tags': typeof AdminLayoutTagsIndexRoute
  '/admin/themes': typeof AdminLayoutThemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/posts/$id': typeof AdminLayoutPostsIdRoute
  '/admin/_layout/posts/new': typeof AdminLayoutPostsNewRoute
  '/admin/_layout/categories/': typeof AdminLayoutCategoriesIndexRoute
  '/admin/_layout/comments/': typeof AdminLayoutCommentsIndexRoute
  '/admin/_layout/media/': typeof AdminLayoutMediaIndexRoute
  '/admin/_layout/plugins/': typeof AdminLayoutPluginsIndexRoute
  '/admin/_layout/posts/': typeof AdminLayoutPostsIndexRoute
  '/admin/_layout/settings/': typeof AdminLayoutSettingsIndexRoute
  '/admin/_layout/tags/': typeof AdminLayoutTagsIndexRoute
  '/admin/_layout/themes/': typeof AdminLayoutThemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/admin'
    | '/admin/login'
    | '/blog/$slug'
    | '/blog/'
    | '/admin/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/categories/'
    | '/admin/comments/'
    | '/admin/media/'
    | '/admin/plugins/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/themes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/admin/login'
    | '/blog/$slug'
    | '/blog'
    | '/admin'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/media'
    | '/admin/plugins'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/themes'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/admin/_layout'
    | '/admin/login'
    | '/blog/$slug'
    | '/blog/'
    | '/admin/_layout/'
    | '/admin/_layout/posts/$id'
    | '/admin/_layout/posts/new'
    | '/admin/_layout/categories/'
    | '/admin/_layout/comments/'
    | '/admin/_layout/media/'
    | '/admin/_layout/plugins/'
    | '/admin/_layout/posts/'
    | '/admin/_layout/settings/'
    | '/admin/_layout/tags/'
    | '/admin/_layout/themes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/themes/': {
      id: '/admin/_layout/themes/'
      path: '/themes'
      fullPath: '/admin/themes/'
      preLoaderRoute: typeof AdminLayoutThemesIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/tags/': {
      id: '/admin/_layout/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AdminLayoutTagsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings/': {
      id: '/admin/_layout/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminLayoutSettingsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/posts/': {
      id: '/admin/_layout/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminLayoutPostsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/plugins/': {
      id: '/admin/_layout/plugins/'
      path: '/plugins'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AdminLayoutPluginsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/media/': {
      id: '/admin/_layout/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminLayoutMediaIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/comments/': {
      id: '/admin/_layout/comments/'
      path: '/comments'
      fullPath: '/admin/comments/'
      preLoaderRoute: typeof AdminLayoutCommentsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/categories/': {
      id: '/admin/_layout/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminLayoutCategoriesIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/posts/new': {
      id: '/admin/_layout/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminLayoutPostsNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/posts/$id': {
      id: '/admin/_layout/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminLayoutPostsIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutPostsIdRoute: typeof AdminLayoutPostsIdRoute
  AdminLayoutPostsNewRoute: typeof AdminLayoutPostsNewRoute
  AdminLayoutCategoriesIndexRoute: typeof AdminLayoutCategoriesIndexRoute
  AdminLayoutCommentsIndexRoute: typeof AdminLayoutCommentsIndexRoute
  AdminLayoutMediaIndexRoute: typeof AdminLayoutMediaIndexRoute
  AdminLayoutPluginsIndexRoute: typeof AdminLayoutPluginsIndexRoute
  AdminLayoutPostsIndexRoute: typeof AdminLayoutPostsIndexRoute
  AdminLayoutSettingsIndexRoute: typeof AdminLayoutSettingsIndexRoute
  AdminLayoutTagsIndexRoute: typeof AdminLayoutTagsIndexRoute
  AdminLayoutThemesIndexRoute: typeof AdminLayoutThemesIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutPostsIdRoute: AdminLayoutPostsIdRoute,
  AdminLayoutPostsNewRoute: AdminLayoutPostsNewRoute,
  AdminLayoutCategoriesIndexRoute: AdminLayoutCategoriesIndexRoute,
  AdminLayoutCommentsIndexRoute: AdminLayoutCommentsIndexRoute,
  AdminLayoutMediaIndexRoute: AdminLayoutMediaIndexRoute,
  AdminLayoutPluginsIndexRoute: AdminLayoutPluginsIndexRoute,
  AdminLayoutPostsIndexRoute: AdminLayoutPostsIndexRoute,
  AdminLayoutSettingsIndexRoute: AdminLayoutSettingsIndexRoute,
  AdminLayoutTagsIndexRoute: AdminLayoutTagsIndexRoute,
  AdminLayoutThemesIndexRoute: AdminLayoutThemesIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
